gpu_id: 0
workers: 4
data_dir: "../Train"
train_flist: "./filelists/train_filelist.txt"
test_flist: "./filelists/test_filelist.txt"
batchSize: 64
lr: 0.005
weight_decay: 0.001
max_epochs: 150
print_freq: 15
checkpoint_folder: "./checkpoints"
init_model: "checkpoints/ResidualRNNConv.pth"
topk: 5
scheduler_patience: 10
